Repository libsv/go-bt, pull requests merged in 2020-11, with the labels that each got.

#1 Upgraded tests, minor fixes, optimizations and more!
  .github/workflows/codeql-analysis.yml
  .gitignore
  .golangci.yml
  .goreleaser.yml
  .make/Makefile.common
  .make/Makefile.go
  .travis.yml
  Makefile
  README.md
  bscript/address.go
  bscript/address_test.go
  bscript/addressvalidation.go
  bscript/addressvalidation_test.go
  bscript/bip276.go
  bscript/bip276_test.go
  bscript/oppushdata.go
  bscript/oppushdata_test.go
  bscript/script.go
  bscript/script_test.go
  bscript/unlockingscript.go
  bytemanipulation_test.go
  crypto/encryption.go
  crypto/hash.go
  crypto/hash_test.go
  fees.go
  fees_test.go
  go.mod
  go.sum
  input.go
  input_test.go
  internalsigner.go
  internalsigner_test.go
  output.go
  output_test.go
  signaturehash.go
  signaturehash_test.go
  tx.go
  tx_test.go
  varint.go
  varint_test.go
Labels: refactor, tests, update

#3 Develop to Master (Updates)
  .github/IMAGES/github-share-image.png
  .github/dependabot.yml
  CODE_STANDARDS.md
  README.md
  bscript/script.go
  examples/create_tx/create_tx.go
  examples/create_tx_with_opreturn/create_tx_with_opreturn.go
  fees.go
  fees_test.go
  go.mod
  go.sum
  input_test.go
  signaturehash.go
  tx.go
  tx_test.go
Labels: tests, update

#4 Develop to Master (Tests, Examples)
  crypto/encryption_test.go
  crypto/hash_test.go
  fees.go
  go.sum
  input_test.go
  internalsigner.go
  output_test.go
  tx_test.go
  varint_test.go
Labels: tests, update

#5 A couple extra features
  .github/workflows/run-tests.yml
  .make/Makefile.go
  .travis.yml
  README.md
  bscript/addressvalidation.go
  bscript/addressvalidation_test.go
  bscript/bip276.go
  bscript/bip276_test.go
  bscript/oppushdata.go
  bscript/oppushdata_test.go
  bscript/script.go
  bscript/script_test.go
  bscript/unlockingscript_test.go
  examples/create_tx/create_tx.go
  examples/create_tx_with_opreturn/create_tx_with_opreturn.go
  go.mod
  go.sum
  internalsigner.go
  internalsigner_test.go
  output.go
  output_test.go
  signer.go
  tx.go
  tx_test.go
Labels: enhancement, tests, update
