Repository libsv/go-bt, pull requests merged in 2021-09, with the labels that each got.

#42 Feat/tx fees
  tx.go
  tx_test.go
  txchange.go
  txchange_test.go
Labels: feature

#43 Fix: False positive with IsFeePaidEnough
  tx.go
Labels: bug-P3

#44 Enhancement: EstimateIsFeePaidEnough
  tx.go
  tx_test.go
Labels: feature

#45 Feature: FromUTXOs
  examples/create_tx/create_tx.go
  examples/create_tx_with_opreturn/create_tx_with_opreturn.go
  tx.go
  tx_test.go
  txinput.go
  txinput_test.go
  utxo.go
Labels: enhancement

#46 Feature: SignAll - General case tx signing.
  examples/create_tx/create_tx.go
  examples/create_tx_with_opreturn/create_tx_with_opreturn.go
  localsigner.go
  localsigner_test.go
  signer.go
  tx_test.go
  txchange_test.go
  txsign.go
  txsign_test.go
Labels: feature

#49 Update: Repo Assets (Minor Updates)
  .github/CODE_OF_CONDUCT.md
  .github/CODE_STANDARDS.md
  .github/CONTRIBUTING.md
  .github/IMAGES/github-share-image.png
  .github/SECURITY.md
  .github/mergify.yml
  .github/workflows/run-tests.yml
  .golangci.yml
  README.md
  bscript/address.go
  bscript/bip276.go
  bscript/interpreter/doc.go
  bscript/interpreter/engine.go
  bscript/interpreter/engine_test.go
  bscript/interpreter/error.go
  bscript/interpreter/opcodeparser.go
  bscript/interpreter/scriptnum.go
  bscript/interpreter/thread.go
  bscript/script.go
  bscript/unlockingscript_test.go
  examples/create_tx/create_tx.go
  examples/create_tx_with_opreturn/create_tx_with_opreturn.go
  fees.go
  fees_test.go
  input.go
  output.go
  sighash/flag.go
  signaturehash.go
  tx.go
  txchange.go
  txinput.go
  varint.go
Labels: update

#51 Enhancement: Smaller Interpreter Suggestion Footprint
  bscript/interpreter/engine.go
  bscript/interpreter/engine_test.go
  bscript/interpreter/errs/error.go
  bscript/interpreter/errs/error_test.go
  bscript/interpreter/example_test.go
  bscript/interpreter/opcodeparser.go
  bscript/interpreter/opcodeparser_test.go
  bscript/interpreter/operations.go
  bscript/interpreter/reference_test.go
  bscript/interpreter/scriptflag/scriptflag.go
  bscript/interpreter/scriptnum.go
  bscript/interpreter/scriptnum_test.go
  bscript/interpreter/stack.go
  bscript/interpreter/stack_test.go
  bscript/interpreter/thread.go
Labels: enhancement

#55 Fix private index field on Output
  output.go
  tx.go
Labels: bug-P3

#50 Feature: JSON Marshalling and Unmarshalling for bt.UTXO
  utxo.go
  utxo_test.go
Labels: feature
