Repository libsv/go-bt, pull requests merged in 2021-08, with the labels that each got.

#33 Change calc update
  txchange.go
  txchange_test.go
Labels: bug

#35 updating pipeline to auto release on tag. adding mergify config
  .github/mergify.yml
  .github/workflows/run-tests.yml
  .make/go.mk
Labels: chore

#18 Enhancement/fee quotes
  bscript/address.go
  fees.go
  fees_test.go
  txchange.go
  txchange_test.go
  txsign_test.go
Labels: enhancement, feature

#36 update to go1.16 and add mergify button
  README.md
  go.mod
Labels: update

#37 Marshal/ Unmarshal feeQuote
  fees.go
  fees_test.go
Labels: enhancement

#38 Fix linter that runs during tests to work on linux.
  .gitignore
  .make/go.mk
Labels: bug-P3

#40 data fee default was incorrect, now fixed
  fees.go
  fees_test.go
  txchange.go
  txchange_test.go
Labels: bug-P3
