Repository libsv/go-bt, pull requests merged in 2021-05, with the labels that each got.

#22 Fix oppushdata overflow bug
  bscript/oppushdata.go
  bscript/oppushdata_test.go
Labels: bug

#24 adding changeToAddress
  bscript/address.go
  txchange.go
  txchange_test.go
Labels: enhancement

#27 adding dust limit to change methods
  tx.go
  tx_test.go
Labels: bug, enhancement
